name: alt
version: 0.1.0
github: "hansjhoffman/alt-lang"
license: BSD3
author: "Hans Hoffman"
maintainer: "@hansjhoffman"
copyright: "Copyright (c) 2021-present, Hans Hoffman"

extra-source-files:
  - README.md
  - CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
category: Compiler, Language

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/hansjhoffman/alt-lang#readme>

dependencies:
  - base >= 4.7 && < 5
  - pretty-simple
  - text

library:
  source-dirs: src

executables:
  alt:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - alt

tests:
  alt-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - alt
      - hspec
